services:
#    blog.example:
#        class: BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
# Fixtures services
    BlogBundle\DataFixtures\ORM\Fixtures:
        tags: [doctrine.fixture.orm]

# This is probably heresy but it works.
    BlogBundle\EventSubscriber\UserRegisteredSubscriber:
        tags: [kernel.event_subscriber]
        arguments: ["@mailer", "@twig"]
